-- Undo for V3__seed_berth_types.sql
-- Remove seeded berth types (keep if referenced elsewhere)
DELETE FROM berth_type WHERE berth_type_name IN (
  'SLEEPER_LOWER','SLEEPER_MIDDLE','SLEEPER_UPPER','SLEEPER_SIDE_LOWER','SLEEPER_SIDE_UPPER',
  'AC3_UPPER','AC3_MIDDLE','AC3_LOWER','AC3_SIDE_LOWER','AC3_SIDE_UPPER',
  'AC2_LOWER','AC2_UPPER','AC2_SIDE_UPPER','AC2_SIDE_LOWER',
  'AC1_LOWER_CABIN','AC1_UPPER_CABIN','AC1_COUPE_LOWER','AC1_COUPE_UPPER',
  'CC_WINDOW','CC_MIDDLE','CC_AISLE','EC_AISLE','EC_WINDOW','GENERAL_SEAT'
);

